---

purge_version: 375
driver_version: 367.35

cuda_os_distribution: "{{ ansible_distribution | lower }}"
cuda_major_version: 8
cuda_package_version: 0.61_375.26

# Ubuntu
ubuntu_version: "{{ ansible_distribution_version.split('.') | join('') }}"
cuda_deb_url: http://developer.download.nvidia.com/compute/cuda/repos/{{ cuda_os_distribution }}{{ ubuntu_version }}/x86_64/cuda-repo-{{ cuda_os_distribution }}{{ ubuntu_version }}_{{ cuda_version }}.{{ cuda_package_version }}_amd64.deb
